name: Build image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/sampozki/derpiina:latest
        docker images

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
    - name: Push the image to ghcr
      run: docker push ghcr.io/sampozki/derpiina:latest